---
- name: Deploy and configure web server
  hosts: localhost
  become: yes
  
  tasks:
    - name: Install Apache Web Server
      package:
        name: apache2
        state: latest

    - name: Copy HTML file to document root directory
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Configure Apache to serve the HTML file as default
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        line: "DocumentRoot /var/www/html"
        state: present

    - name: Configure Apache to redirect all HTTP requests to HTTPS
      lineinfile:
        path: /etc/apache2/sites-available/default-ssl.conf
        line: "Redirect / https://{{ ansible_fqdn }}/"
        state: present

    - name: Generate self-signed SSL certificate
      shell: |
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -subj "/C=US/ST=California/L=San Francisco/O=Example Company/CN={{ ansible_fqdn }}"

    - name: Configure Apache to use the SSL certificate
      lineinfile:
        path: /etc/apache2/sites-available/default-ssl.conf
        line: |
          SSLEngine on
          SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
          SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key

    - name: Configure firewall to allow only HTTPS traffic
      ufw:
        rule: allow
        port: 443/tcp
        state: enabled
      tags: firewall
